kind: pipeline
name: pomodoro

steps:
- name: test
  image: node:16.14.2-alpine
  environment:
    HOST: 0
    PORT: 5000
  commands:
  - npm install
  - npm run build
- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: username
    password: 
      from_secret: password
    auto_tag: true
    repo: registry.digitalocean.com/php-app
    registry: registry.digitalocean.com
    debug: true
    
